/**
 * The random word pool.
 *
 * Every entry carries a one-line definition, because a rep should fail on your
 * mind-to-mouth connection, not on not knowing what the word means.
 *
 * The pool was audited against two psycholinguistic datasets — Brysbaert et al.
 * (2014) concreteness norms and Warriner et al. (2013) valence and arousal
 * norms. Words that scored flat on both dimensions (nothing to picture, nothing
 * felt) were cut: they produce a stall at twenty seconds no matter how good the
 * speaker is, which teaches nothing. Words kept in the concrete list either
 * carry emotional weight or have a settled figurative sense to reach for.
 */

export type WordCategory = "concrete" | "abstract" | "action" | "quality";

export const CATEGORY_LABEL: Record<WordCategory, string> = {
  concrete: "thing",
  abstract: "concept",
  action: "action",
  quality: "quality",
};

/** [word, primary definition, difficulty tier 1-5] */
type Entry = readonly [string, string, number];

/** Things you can point at. Easiest entry, so they need a second layer. */
const CONCRETE: Entry[] = [
  ["grave", "the hole in the ground where a body is buried", 1],
  ["pigeon", "a stout grey bird that gathers in city flocks", 2],
  ["monkey", "a small, agile, usually long-tailed primate", 1],
  ["anchor", "a heavy hook dropped to hold a boat in place", 3],
  ["lantern", "a portable lamp with a case around the flame", 2],
  ["staircase", "a set of steps between the floors of a building", 3],
  ["compass", "an instrument with a needle that points north", 2],
  ["harbor", "a sheltered stretch of water where ships can rest", 2],
  ["mirror", "a polished surface that reflects what is in front of it", 1],
  ["bridge", "a structure built to carry a path over a gap", 2],
  ["violin", "a small wooden string instrument played with a bow", 1],
  ["passport", "an official booklet that lets you cross borders", 1],
  ["chalk", "a soft white stone used for writing on boards", 3],
  ["elevator", "a moving box that carries people between floors", 2],
  ["typewriter", "a machine that prints letters onto paper as you strike keys", 2],
  ["greenhouse", "a glass building where plants are grown in warmth", 1],
  ["suitcase", "a stiff case with a handle for carrying clothes", 2],
  ["hammock", "a hanging bed of fabric slung between two points", 1],
  ["candle", "a stick of wax with a wick that burns for light", 1],
  ["cathedral", "the principal church of a district, usually vast", 2],
  ["postcard", "a stiff card with a picture, mailed without an envelope", 2],
  ["telescope", "a tube of lenses that makes distant things look near", 1],
  ["bicycle", "a two-wheeled vehicle driven by pedals", 1],
  ["attic", "the storage space directly under a roof", 3],
  ["lighthouse", "a tower whose light warns ships away from rocks", 1],
  ["playground", "an outdoor area with equipment for children to play on", 1],
  ["windmill", "a tower with sails turned by the wind to do work", 1],
  ["aquarium", "a glass tank, or a building of them, holding live fish", 1],
  ["campfire", "an open fire built outdoors for warmth and company", 1],
  ["corridor", "a long passage with rooms opening off it", 3],
  ["ladder", "two side rails joined by rungs, used for climbing", 2],
  ["mailbox", "a box where letters are left or collected", 1],
  ["notebook", "a bound set of blank pages for writing in", 1],
  ["parachute", "a canopy that slows a fall through the air", 2],
  ["umbrella", "a folding canopy on a stick that keeps rain off", 2],
  ["wallet", "a small folding case for money and cards", 1],
  ["balcony", "a platform projecting from an upper wall of a building", 2],
  ["chandelier", "a hanging light fixture with many branches", 1],
  ["engine", "a machine that turns fuel into motion", 2],
  ["fireplace", "a recess in a wall where a fire is built indoors", 1],
  ["glacier", "a slow river of ice moving down a valley", 2],
  ["hospital", "a building where the sick and injured are treated", 1],
  ["island", "a piece of land surrounded by water", 1],
  ["kitchen", "the room in which food is prepared", 1],
  ["library", "a collection of books, or the building holding it", 1],
  ["museum", "a building where objects of value are kept and shown", 1],
  ["newspaper", "printed sheets carrying the day's news", 3],
  ["orchard", "a piece of land planted with fruit trees", 2],
  ["pavement", "the hard surface of a road or footpath", 2],
  ["runway", "the strip of ground a plane uses to take off and land", 2],
  ["stadium", "a large arena with tiered seating around a field", 1],
  ["tunnel", "a passage dug underground or through a hill", 2],
  ["vineyard", "a plantation of grapevines grown for wine", 1],
  ["warehouse", "a large building where goods are stored", 2],
  ["airport", "the place where aircraft take off, land, and are boarded", 1],
  ["basement", "the floor of a building below ground level", 3],
  ["desert", "a barren land with almost no rainfall", 2],
  ["factory", "a building where goods are manufactured in quantity", 3],
  ["garden", "a plot of ground where plants are deliberately grown", 1],
  ["ice", "frozen water, solid and cold to the touch", 1],
  ["jacket", "a short coat worn on the upper body", 2],
  ["knife", "a blade with a handle, used for cutting", 1],
  ["laundry", "clothes waiting to be washed, or the washing of them", 2],
  ["needle", "a thin pointed steel shaft used for sewing", 1],
  ["ocean", "the vast body of salt water covering most of the earth", 1],
  ["piano", "a keyboard instrument sounded by hammers striking strings", 1],
  ["rope", "thick cord made by twisting strands together", 2],
  ["shadow", "the dark shape cast when something blocks light", 3],
  ["thread", "a fine strand of spun fibre used in sewing", 2],
  ["volcano", "a mountain that erupts molten rock from below", 1],
  ["whistle", "a sharp sound made through the lips, or the device that makes it", 3],
  ["yard", "an enclosed piece of ground beside a building", 2],
  ["mask", "a covering worn over the face to hide or protect it", 2],
  ["scar", "the mark left on skin after a wound heals", 1],
  ["storm", "violent weather of wind, rain, or snow", 1],
  ["echo", "a sound reflected back to the listener", 4],
  ["wall", "an upright structure that encloses or divides", 3],
  ["door", "a hinged panel that opens and closes an entrance", 2],
  ["map", "a drawing of an area showing where things are", 2],
  ["clock", "a device that shows the time", 2],
  ["crowd", "a large group of people gathered in one place", 1],
  ["stage", "the raised platform a performer stands on", 2],
  ["fire", "burning that gives off heat, light, and flame", 1],
  ["key", "a shaped piece of metal that opens a lock", 1],
  ["seed", "the small unit a plant grows from", 1],
  ["ghost", "the spirit of a dead person, imagined as visible", 2],
  ["root", "the part of a plant that anchors it and draws water", 3],
  ["mountain", "a very large natural rise of land, far higher than a hill", 1],
  ["river", "a large natural stream of water flowing to the sea", 1],
  ["forest", "a large area thickly covered with trees", 1],
  ["cave", "a natural hollow running back into a hill or cliff", 2],
  ["valley", "the low ground between two ranges of hills", 2],
  ["cliff", "a steep rock face, usually at the edge of the sea", 1],
  ["waterfall", "a stream of water falling from a height", 1],
  ["rain", "water falling from the clouds in drops", 1],
  ["snow", "frozen water falling as soft white flakes", 1],
  ["thunder", "the deep crash of sound that follows lightning", 1],
  ["moon", "the body that orbits the earth and lights the night", 1],
  ["cloud", "a visible mass of water droplets floating in the sky", 2],
  ["wind", "air moving across the ground, felt but not seen", 3],
  ["tide", "the daily rise and fall of the sea", 1],
  ["canyon", "a deep gorge cut through rock by a river", 2],
  ["meadow", "a field of grass and wildflowers", 1],
  ["jungle", "dense tropical forest tangled with vegetation", 2],
  ["dune", "a hill of sand shaped by the wind", 3],
  ["horizon", "the line where the land or sea meets the sky", 1],
  ["rainbow", "an arc of colour thrown across the sky by sunlight and rain", 1],
  ["frost", "a thin white coating of ice on a cold surface", 2],
  ["fog", "thick cloud at ground level that hides what is ahead", 2],
  ["hill", "a raised area of land, lower than a mountain", 2],
  ["lake", "a large body of water surrounded by land", 1],
  ["tree", "a tall plant with a woody trunk and branches", 1],
  ["flower", "the coloured part of a plant that carries its seed", 1],
  ["leaf", "the flat green part growing from the stem of a plant", 1],
  ["thorn", "a sharp point growing from the stem of a plant", 1],
  ["harvest", "the gathering in of a season's crops", 2],
  ["soil", "the top layer of earth that plants grow in", 3],
  ["stone", "a small piece of rock", 3],
  ["sand", "the fine loose grains that make up a beach or desert", 1],
  ["dust", "fine dry powder that settles on everything left still", 2],
  ["smoke", "the grey cloud that rises from something burning", 1],
  ["ash", "the grey powder left after something has burned", 1],
  ["mud", "wet soft earth", 3],
  ["horse", "a large four-legged animal ridden or used to pull loads", 1],
  ["wolf", "a wild animal of the dog family that hunts in a pack", 1],
  ["bear", "a large heavy wild animal with thick fur and claws", 2],
  ["owl", "a night-hunting bird with large forward-facing eyes", 1],
  ["eagle", "a large bird of prey with exceptional eyesight", 1],
  ["elephant", "the largest land animal, with a trunk and thick grey skin", 1],
  ["butterfly", "an insect with large patterned wings, once a caterpillar", 1],
  ["whale", "the largest sea animal, a mammal that breathes air", 1],
  ["rabbit", "a small burrowing animal with long ears", 1],
  ["fox", "a wild animal of the dog family, red-brown and quick", 2],
  ["deer", "a graceful wild animal, the male often carrying antlers", 1],
  ["mouse", "a small rodent with a pointed nose and long thin tail", 3],
  ["ant", "a small social insect that lives in a large colony", 1],
  ["moth", "a night-flying insect drawn helplessly toward light", 2],
  ["crow", "a large glossy black bird with a harsh call", 2],
  ["swan", "a large white water bird with a long curved neck", 1],
  ["dolphin", "an intelligent sea mammal that swims in groups", 1],
  ["turtle", "a slow reptile carrying a hard shell on its back", 1],
  ["chair", "a seat with a back, for one person", 2],
  ["roof", "the covering over the top of a building", 2],
  ["ceiling", "the upper surface of a room, seen from inside", 2],
  ["lamp", "a device that gives light where you need it", 2],
  ["blanket", "a thick cloth covering that keeps you warm", 1],
  ["pillow", "a soft cushion for resting your head on", 1],
  ["curtain", "a hanging cloth that covers a window or a stage", 2],
  ["carpet", "a thick woven floor covering", 2],
  ["drawer", "a sliding box built into furniture for storing things", 3],
  ["shelf", "a flat board fixed to a wall for holding things", 2],
  ["sink", "a fixed basin with a tap and a drain", 3],
  ["towel", "a cloth for drying yourself", 1],
  ["soap", "a substance used with water for washing", 1],
  ["razor", "a blade for shaving hair from the skin", 2],
  ["watch", "a small clock worn on the wrist", 3],
  ["ring", "a circular band worn on a finger", 1],
  ["glove", "a covering for the hand with a place for each finger", 1],
  ["boot", "a sturdy shoe that covers the ankle or higher", 2],
  ["scarf", "a length of cloth worn around the neck", 1],
  ["button", "a small disc that fastens a garment through a hole", 2],
  ["pocket", "a small pouch sewn into clothing for carrying things", 2],
  ["belt", "a strap worn around the waist", 2],
  ["uniform", "identical clothing worn by everyone in a group", 2],
  ["bread", "a staple food baked from flour and water", 1],
  ["salt", "the white mineral used to season and preserve food", 1],
  ["honey", "the sweet syrup made by bees", 1],
  ["coffee", "a hot drink brewed from roasted ground beans", 1],
  ["wine", "an alcoholic drink made from fermented grapes", 2],
  ["milk", "the white liquid mammals feed to their young", 1],
  ["apple", "a round firm fruit with crisp flesh", 1],
  ["lemon", "a sour yellow citrus fruit", 1],
  ["egg", "the oval shell a bird's young grows inside", 2],
  ["recipe", "a set of instructions for making a dish", 1],
  ["village", "a small settlement, smaller than a town", 2],
  ["market", "a place where goods are bought and sold in the open", 2],
  ["station", "the place where trains or buses stop for passengers", 3],
  ["bakery", "a shop where bread and cakes are baked and sold", 1],
  ["theater", "a building where plays are performed to an audience", 1],
  ["gallery", "a room or building where art is displayed", 1],
  ["hotel", "a building where travellers pay to sleep", 1],
  ["farm", "land and buildings used for growing crops or raising animals", 2],
  ["pier", "a platform built out over the water", 2],
  ["border", "the line where one country or territory meets another", 3],
  ["crossroads", "the point where two roads meet and you must choose", 2],
  ["alley", "a narrow passage between or behind buildings", 2],
  ["rooftop", "the flat top of a building, seen from above", 2],
  ["threshold", "the strip of floor beneath a doorway, and the point of entering", 4],
  ["gate", "a hinged barrier in a wall or fence", 2],
  ["fence", "a barrier of posts and rails marking a boundary", 3],
  ["tower", "a tall narrow building, far higher than it is wide", 3],
  ["castle", "a large fortified building from an age of sieges", 1],
  ["ruin", "what remains of a building that has fallen down", 1],
  ["monument", "a structure built so that something is not forgotten", 2],
  ["statue", "a carved or cast figure of a person or animal", 2],
  ["fountain", "an ornamental structure that pushes water into the air", 1],
  ["bench", "a long seat for more than one person", 2],
  ["train", "a line of carriages pulled along a railway", 1],
  ["boat", "a small vessel for travelling on water", 1],
  ["subway", "an underground railway beneath a city", 2],
  ["wheel", "a circular object that turns on an axle", 2],
  ["ticket", "a printed slip that entitles you to enter or travel", 3],
  ["luggage", "the bags a traveller carries their belongings in", 3],
  ["path", "a narrow way worn or made for walking", 3],
  ["hammer", "a tool with a heavy head for driving nails", 2],
  ["drum", "a hollow instrument played by striking a stretched skin", 1],
  ["guitar", "a string instrument played by plucking or strumming", 1],
  ["bell", "a hollow metal object that rings when struck", 1],
  ["camera", "a device that captures images", 1],
  ["microphone", "a device that turns a voice into a signal others can hear", 2],
  ["pen", "a handheld instrument for writing in ink", 2],
  ["letter", "a written message sent to someone", 2],
  ["envelope", "the paper cover a letter is sealed inside", 2],
  ["stamp", "the small printed square that pays for a letter's journey", 2],
  ["diary", "a book in which you record each day", 2],
  ["photograph", "a picture made by a camera", 1],
  ["radio", "a device that receives broadcast sound", 2],
  ["telephone", "a device for speaking to someone far away", 1],
  ["battery", "a cell that stores power until something needs it", 2],
  ["magnet", "a piece of metal that pulls iron towards it", 2],
  ["lens", "a curved piece of glass that bends light to focus it", 3],
  ["hourglass", "a glass vessel that measures time with running sand", 2],
  ["kite", "a light frame flown on a string in the wind", 1],
  ["balloon", "a thin bag inflated with air or gas", 1],
  ["dice", "small cubes thrown to produce a random number", 1],
  ["coin", "a flat piece of metal used as money", 1],
  ["medal", "a metal disc awarded for an achievement", 1],
  ["trophy", "a cup or figure given to the winner", 1],
  ["crown", "the headpiece worn by a monarch", 1],
  ["flag", "a piece of cloth that stands for a country or cause", 2],
  ["hand", "the part of the body at the end of the arm", 2],
  ["voice", "the sound a person makes when speaking or singing", 2],
  ["heartbeat", "one pulse of the heart", 2],
  ["fingerprint", "the pattern of ridges on a fingertip, unique to you", 2],
  ["footprint", "the mark a foot leaves behind", 2],
  ["breath", "one drawing of air into the lungs", 2],
  ["bone", "one of the hard pieces that make up a skeleton", 2],
  ["skin", "the outer covering of the body", 2],
  ["pulse", "the beat of blood you can feel at the wrist", 1],
  ["tongue", "the muscle in the mouth used for tasting and speaking", 1],
  ["smile", "the expression made by turning the mouth up at the corners", 1],
  ["tear", "a drop of liquid that falls from the eye", 1],
  ["wrinkle", "a small line or fold in skin or cloth", 2],
  ["rust", "the red-brown crust that forms on neglected iron", 2],
  ["crack", "a narrow split in a surface", 1],
  ["knot", "a fastening made by tying something together", 2],
  ["stain", "a mark left behind that will not wash out", 1],
  ["spark", "a tiny burning particle thrown from a fire", 1],
  ["ribbon", "a narrow strip of fabric used to tie or decorate", 1],
  ["chain", "a series of connected metal links", 3],
  ["nail", "a thin metal spike hammered in to fasten things", 2],
  ["wire", "a thin flexible thread of metal", 3],
  ["cage", "an enclosure of bars for keeping an animal in", 1],
  ["jar", "a wide-mouthed glass container with a lid", 2],
  ["bottle", "a narrow-necked container for liquid", 2],
  ["basket", "an open container woven from strips", 2],
  ["bucket", "an open cylindrical container with a handle", 2],
];

/** Ideas with no shape. Hardest to picture, easiest to feel. */
const ABSTRACT: Entry[] = [
  ["wonder", "a feeling of surprise mixed with admiration", 5],
  ["grief", "deep sorrow, especially after a death", 2],
  ["momentum", "the force something gathers once it is already moving", 4],
  ["loyalty", "steady allegiance to a person or cause", 4],
  ["nostalgia", "a wistful longing for the past", 5],
  ["chaos", "complete disorder, with no pattern to hold on to", 1],
  ["legacy", "what you leave behind for those who follow", 4],
  ["silence", "the complete absence of sound", 4],
  ["hunger", "the discomfort of needing food, or any craving as strong", 2],
  ["patience", "the ability to wait without frustration", 5],
  ["reputation", "the opinion others generally hold of you", 5],
  ["boundary", "a line marking where one thing ends and another begins", 5],
  ["ritual", "an act repeated the same way for its own meaning", 5],
  ["luck", "success or failure that arrives by chance rather than effort", 5],
  ["debt", "something owed, usually money, until it is paid back", 1],
  ["instinct", "an inborn urge to act without reasoning it through", 5],
  ["identity", "the set of qualities that make someone who they are", 5],
  ["tradition", "a custom passed down from one generation to the next", 5],
  ["ambition", "a strong desire to achieve something", 3],
  ["regret", "sorrow over something you did or failed to do", 4],
  ["trust", "confidence that someone will not let you down", 4],
  ["power", "the capacity to make things or people move", 4],
  ["distance", "the amount of space between two things", 4],
  ["timing", "the choice of when to act, and how well it lands", 5],
  ["control", "the power to direct how something goes", 5],
  ["freedom", "the state of being able to act without restraint", 2],
  ["pressure", "the weight of demands or expectations pressing on you", 3],
  ["belonging", "the sense of being accepted as part of something", 4],
  ["curiosity", "the urge to find out", 3],
  ["discipline", "doing the necessary thing whether or not you feel like it", 3],
  ["envy", "resentful longing for what someone else has", 4],
  ["forgiveness", "letting go of the claim to punish a wrong", 5],
  ["gratitude", "the felt appreciation of what you have been given", 3],
  ["humility", "an honest, unexaggerated view of your own importance", 5],
  ["intuition", "knowing something without being able to say how", 4],
  ["justice", "treatment that gives each person what they are due", 4],
  ["kindness", "the habit of treating others generously", 4],
  ["loneliness", "the ache of being without company you want", 3],
  ["memory", "the mind's record of what happened", 4],
  ["novelty", "the quality of being new, and the pleasure that brings", 4],
  ["obsession", "a thought or desire that will not let you go", 4],
  ["perspective", "the position from which you see something", 5],
  ["resilience", "the ability to recover from difficulty", 4],
  ["sacrifice", "giving up something valued for something valued more", 4],
  ["talent", "a natural aptitude for doing something well", 3],
  ["urgency", "the pressure of needing to act right now", 4],
  ["vulnerability", "openness to being hurt, physically or emotionally", 4],
  ["wisdom", "good judgement built out of experience", 4],
  ["youth", "the period of being young", 3],
  ["authority", "the recognised right to give orders and be obeyed", 4],
  ["burnout", "exhaustion from prolonged stress or overwork", 3],
  ["comfort", "ease of body or relief of distress", 3],
  ["doubt", "uncertainty about what is true or right", 5],
  ["empathy", "the ability to feel what another person is feeling", 4],
  ["failure", "falling short of what you set out to do", 2],
  ["growth", "the process of getting larger or better", 3],
  ["honesty", "telling the truth and not pretending", 4],
  ["innocence", "freedom from guilt, or from knowledge of harm", 5],
  ["judgment", "the ability to weigh things and decide well", 5],
  ["knowledge", "what you know to be true, and how you came to know it", 3],
  ["luxury", "great comfort, usually costly and beyond need", 3],
  ["mortality", "the fact that every living thing dies", 4],
  ["nerves", "anxiety felt in the body before something matters", 4],
  ["opportunity", "a moment when circumstances allow you to act", 3],
  ["privacy", "being free from observation by others", 5],
  ["temptation", "the pull toward something you have decided against", 5],
  ["uncertainty", "not knowing how something will turn out", 4],
  ["waiting", "passing time until something else can happen", 3],
  ["beauty", "the quality that gives deep pleasure to the senses", 1],
  ["chance", "the way events fall out with no cause you can name", 5],
  ["duty", "what you are obliged to do, whether or not you want to", 5],
  ["effort", "the energy deliberately put into doing something", 4],
  ["faith", "confidence held without proof", 5],
  ["guilt", "the feeling of having done wrong", 3],
  ["hope", "the expectation that something good may still happen", 3],
  ["influence", "the power to change what others do without forcing them", 5],
  ["jealousy", "fear of losing what you have to a rival", 3],
  ["karma", "the idea that what you do comes back to you", 5],
  ["loss", "no longer having something you had", 3],
  ["mercy", "kindness shown to someone you could punish instead", 5],
  ["pride", "satisfaction in your own worth, or too much of it", 4],
  ["shame", "the painful sense of having been diminished", 2],
  ["truth", "what is actually the case", 4],
  ["unity", "the state of being joined as a whole", 4],
  ["victory", "winning a contest or struggle", 1],
  ["worry", "anxiety turned over and over in the mind", 1],
  ["courage", "the strength to act despite being afraid", 3],
  ["fear", "the feeling that something bad is about to happen", 1],
  ["anger", "the hot feeling that rises when you are wronged", 2],
  ["joy", "a bright and unguarded happiness", 2],
  ["sorrow", "deep sadness, especially over a loss", 4],
  ["peace", "freedom from conflict or disturbance", 3],
  ["boredom", "the flat restlessness of having nothing to engage you", 4],
  ["anticipation", "the feeling of waiting for something you expect", 5],
  ["awe", "wonder mixed with a sense of your own smallness", 5],
  ["confidence", "the settled belief that you can handle it", 4],
  ["insecurity", "the nagging doubt that you are not enough", 3],
  ["charisma", "the pull some people have on a room", 4],
  ["wit", "quickness of mind that comes out funny", 3],
  ["irony", "saying one thing while plainly meaning another", 5],
  ["betrayal", "being let down by someone who was trusted", 3],
  ["revenge", "harm dealt back to someone who harmed you", 3],
  ["secrecy", "the deliberate keeping of something hidden", 4],
  ["gossip", "talk about people who are not in the room", 4],
  ["fame", "being widely known by strangers", 5],
  ["anonymity", "being unknown, and unbothered because of it", 5],
  ["friendship", "the bond between people who choose each other", 2],
  ["romance", "the feeling and behaviour of being in love", 2],
  ["marriage", "the formal union of two people", 2],
  ["childhood", "the years of being a child", 4],
  ["adulthood", "the state of being fully grown and responsible", 5],
  ["retirement", "leaving working life for good", 3],
  ["generation", "all the people born at roughly the same time", 5],
  ["heritage", "what a culture or family passes down", 4],
  ["exile", "being barred from returning home", 3],
  ["community", "the people among whom you live", 3],
  ["class", "the social layer a person is treated as belonging to", 3],
  ["wealth", "having far more than you need", 2],
  ["poverty", "not having enough to live on", 1],
  ["greed", "wanting more than your share and not stopping", 4],
  ["generosity", "the readiness to give more than is required", 4],
  ["charity", "help given freely to those who need it", 4],
  ["budget", "a plan for what money may be spent on", 4],
  ["career", "the working life a person builds over years", 4],
  ["success", "reaching what you set out to reach", 2],
  ["competition", "the effort to do better than someone else", 2],
  ["teamwork", "people working as one toward the same end", 4],
  ["leadership", "the work of getting others to move together", 4],
  ["mastery", "the point where a skill has stopped being effortful", 2],
  ["habit", "something you do without deciding to", 5],
  ["routine", "a fixed sequence you repeat without thinking", 5],
  ["procrastination", "putting off what you have already decided to do", 4],
  ["motivation", "the reason that gets you moving", 4],
  ["willpower", "the force used to make yourself do the hard thing", 4],
  ["distraction", "anything that pulls attention off the task", 5],
  ["attention", "the mental spotlight, and where you point it", 4],
  ["imagination", "the mind's ability to picture what is not there", 4],
  ["creativity", "the making of something that did not exist", 3],
  ["inspiration", "the sudden arrival of an idea worth acting on", 4],
  ["originality", "the quality of not being copied from anywhere", 4],
  ["invention", "something made for the first time", 3],
  ["discovery", "the finding of something that was already there", 2],
  ["progress", "movement toward a better state", 5],
  ["technology", "the tools a society builds to extend itself", 4],
  ["surveillance", "close watching, usually without consent", 2],
  ["censorship", "the suppression of what may be said", 5],
  ["democracy", "rule by the people, through their votes", 4],
  ["revolution", "the forcible overturning of an established order", 3],
  ["protest", "a public objection to something wrong", 4],
  ["bureaucracy", "the layers of procedure between you and a decision", 5],
  ["hierarchy", "the ranking of people by rank or importance", 5],
  ["punishment", "something unpleasant imposed for a wrong done", 2],
  ["redemption", "the winning back of something you had forfeited", 5],
  ["conscience", "the inner sense of right and wrong", 5],
  ["morality", "the principles separating right conduct from wrong", 5],
  ["integrity", "being the same person whether or not you are watched", 5],
  ["hypocrisy", "demanding of others what you do not do yourself", 4],
  ["prejudice", "an opinion formed before any of the facts", 2],
  ["stereotype", "a fixed idea about a group, applied to an individual", 4],
  ["tolerance", "allowing what you do not agree with", 5],
  ["respect", "regard for the worth of a person or thing", 4],
  ["dignity", "the worth a person holds simply by being one", 4],
  ["humiliation", "being made small in front of others", 2],
  ["embarrassment", "the flush of being caught out in public", 2],
  ["intimacy", "closeness in which nothing is being hidden", 2],
  ["affection", "a warm liking for someone", 2],
  ["devotion", "loyalty so deep it shapes what you do", 4],
  ["longing", "wanting something distant, and feeling the distance", 4],
  ["desire", "a strong wish for something", 3],
  ["satisfaction", "the settled feeling of enough", 4],
  ["happiness", "a lasting sense that life is going well", 1],
  ["despair", "the loss of all hope", 4],
  ["optimism", "the tendency to expect things to go well", 4],
  ["cynicism", "the assumption that everyone acts from self-interest", 4],
  ["superstition", "a belief in influences that cannot be shown to exist", 4],
  ["ceremony", "a formal act performed because the occasion demands it", 3],
  ["festival", "a period of public celebration", 1],
  ["anniversary", "the yearly return of a date that mattered", 3],
  ["milestone", "a point that marks how far you have come", 2],
  ["deadline", "the time by which something must be finished", 2],
  ["haste", "doing something too fast to do it well", 5],
  ["stillness", "the absence of movement, and the quiet in it", 5],
  ["rhythm", "a pattern of beats repeating in time", 2],
  ["harmony", "different parts agreeing rather than clashing", 3],
  ["contrast", "the difference that shows when two things sit together", 5],
  ["simplicity", "having no more parts than are needed", 4],
  ["complexity", "being made of many parts that interact", 5],
  ["clarity", "being easy to understand, with nothing muddled", 4],
  ["confusion", "not being able to make sense of it", 4],
  ["mystery", "something that resists being explained", 5],
  ["secret", "something deliberately kept from other people", 5],
  ["compromise", "a settlement where each side gives something up", 5],
  ["conflict", "a serious disagreement between people or forces", 3],
  ["suspicion", "the sense that something is not right", 3],
  ["anxiety", "unease about something that has not happened yet", 3],
  ["panic", "fear that arrives all at once and takes over", 1],
  ["relief", "the loosening that comes when a worry lifts", 4],
  ["exhaustion", "being emptied of energy", 3],
  ["inertia", "the tendency to keep doing exactly what you were doing", 4],
  ["obstacle", "something in the way of where you are going", 3],
  ["setback", "a reverse that costs you ground you had gained", 5],
  ["fate", "the idea that events are already settled", 5],
  ["coincidence", "two things lining up with no cause between them", 5],
  ["risk", "exposure to the chance that it goes wrong", 4],
  ["consequence", "what follows from what you did", 4],
  ["responsibility", "being the one answerable for it", 5],
  ["blame", "the assigning of fault for something gone wrong", 3],
  ["recognition", "being seen and credited for what you did", 4],
  ["criticism", "judgement passed on the faults of something", 3],
  ["praise", "the open expression of approval", 1],
  ["certainty", "having no doubt at all", 5],
  ["evidence", "what can be shown in support of a claim", 4],
  ["belief", "holding something to be true", 5],
  ["opinion", "a view held without needing to be proved", 5],
  ["bias", "a leaning that bends your judgement without your noticing", 5],
  ["compassion", "concern for suffering, with the urge to relieve it", 3],
  ["cruelty", "taking pleasure in causing pain", 2],
  ["strength", "the capacity to bear weight or resistance", 2],
  ["weakness", "the point at which something gives way", 3],
  ["endurance", "the ability to keep going long past comfort", 3],
  ["noise", "unwanted sound", 1],
  ["music", "sound arranged so that it means something", 1],
  ["melody", "the line of a tune you can hum back", 1],
  ["language", "the system of words a people share", 5],
  ["accent", "the way your origins sound in your speech", 2],
  ["slang", "informal words a group uses among themselves", 5],
  ["vocabulary", "the stock of words a person can reach for", 5],
  ["metaphor", "describing one thing as if it were another", 5],
  ["poetry", "writing arranged for its sound and compression", 3],
  ["myth", "an old story a culture tells to explain itself", 5],
  ["legend", "a story handed down and half believed", 2],
  ["history", "the record of what happened before now", 4],
  ["future", "the time that has not arrived yet", 3],
  ["forgetting", "the losing of what you once held in mind", 4],
  ["sleep", "the nightly state in which the mind lets go", 1],
  ["insomnia", "lying awake when you badly need to sleep", 2],
  ["vacation", "time deliberately taken away from work", 1],
  ["adventure", "an undertaking with real risk and no guaranteed end", 1],
  ["home", "the place you are from, or the place you return to", 1],
  ["shelter", "cover from weather or danger", 1],
  ["safety", "being out of reach of harm", 4],
  ["danger", "the possibility of being harmed", 1],
  ["survival", "staying alive when that was in doubt", 2],
  ["thirst", "the need for water, and any want as sharp", 4],
  ["appetite", "the desire for food, or for anything else", 3],
];

/** Verbs. The awkward middle: hard to picture, hard to feel, easy to fumble. */
const ACTION: Entry[] = [
  ["eliminate", "to remove something completely", 4],
  ["wander", "to move about with no fixed destination", 5],
  ["negotiate", "to reach agreement by discussion and trade-offs", 5],
  ["collapse", "to fall down suddenly, or give way under strain", 1],
  ["rehearse", "to practise a performance before giving it", 4],
  ["gamble", "to risk something on an uncertain outcome", 3],
  ["borrow", "to take something on the understanding you return it", 4],
  ["escape", "to get free from a place or situation", 4],
  ["translate", "to put words from one language into another", 5],
  ["interrupt", "to break in on something already in progress", 3],
  ["rebuild", "to build again what was damaged or lost", 3],
  ["surrender", "to stop resisting and give yourself up", 4],
  ["improvise", "to make something up as you go, without preparation", 5],
  ["commute", "to travel regularly between home and work", 3],
  ["apologize", "to say you are sorry for something you did", 5],
  ["compete", "to strive against others for the same thing", 5],
  ["experiment", "to try something out to see what happens", 3],
  ["forgive", "to stop holding a wrong against someone", 4],
  ["gather", "to bring scattered things or people together", 5],
  ["hesitate", "to pause before acting, out of doubt", 5],
  ["imitate", "to copy the way someone else does something", 5],
  ["listen", "to give attention to sound, especially to someone speaking", 3],
  ["migrate", "to move from one region to another to live", 4],
  ["notice", "to become aware of something", 4],
  ["observe", "to watch closely and take in detail", 5],
  ["practice", "to do something repeatedly in order to get better", 5],
  ["question", "to ask about something, or to doubt it", 3],
  ["recover", "to return to health, or to get something back", 4],
  ["teach", "to help someone come to know or do something", 3],
  ["volunteer", "to offer to do something without being asked or paid", 2],
  ["adapt", "to change so as to fit new conditions", 5],
  ["balance", "to hold competing things in a workable proportion", 3],
  ["celebrate", "to mark an occasion with enjoyment", 1],
  ["decide", "to settle on one option and close the others", 5],
  ["endure", "to bear something painful without giving way", 5],
  ["focus", "to concentrate attention on one thing", 4],
  ["grow", "to increase in size, number, or maturity", 4],
  ["hide", "to put out of sight, or to stay out of sight", 5],
  ["invest", "to put money, time, or effort in for a later return", 5],
  ["juggle", "to keep several things going at once", 2],
  ["lead", "to go first and have others follow", 3],
  ["outgrow", "to become too big or too developed for something", 5],
  ["persuade", "to bring someone round to your view", 5],
  ["quit", "to stop doing something, often for good", 4],
  ["start", "to begin something, or to set it in motion", 3],
  ["trade", "to give one thing in exchange for another", 4],
  ["vanish", "to disappear suddenly and completely", 3],
  ["warn", "to tell someone of a danger ahead", 4],
  ["argue", "to disagree in words, or to make a case", 1],
  ["believe", "to accept something as true", 5],
  ["change", "to become different, or to make something so", 5],
  ["dream", "to picture something while asleep, or to long for it awake", 3],
  ["explain", "to make something clear to someone else", 5],
  ["fail", "to not succeed at what you attempted", 1],
  ["give", "to hand something over without asking for return", 2],
  ["help", "to make things easier for someone", 3],
  ["invite", "to ask someone to come or to take part", 3],
  ["leave", "to go away from a place or a person", 5],
  ["open", "to make something no longer closed", 3],
  ["promise", "to commit yourself to doing something", 5],
  ["reach", "to stretch out for something, or to arrive at it", 3],
  ["share", "to let others have a part of what is yours", 4],
  ["try", "to make an attempt", 5],
  ["understand", "to grasp the meaning of something", 4],
  ["win", "to come first in a contest", 2],
  ["build", "to make something by putting parts together", 3],
  ["repair", "to put right something that has broken", 5],
  ["create", "to bring something into existence", 1],
  ["destroy", "to damage something so badly it no longer exists", 1],
  ["design", "to plan the form of something before it is made", 3],
  ["prepare", "to get ready before the thing itself begins", 5],
  ["organize", "to arrange things into working order", 4],
  ["choose", "to settle on one thing over the others", 5],
  ["refuse", "to say no to something offered or demanded", 3],
  ["insist", "to keep saying it after being pushed back", 5],
  ["demand", "to ask for something as though owed it", 3],
  ["deliver", "to bring something to where it was meant to go", 3],
  ["collect", "to gather things together over time", 4],
  ["protect", "to keep something from being harmed", 3],
  ["defend", "to hold off an attack or an accusation", 4],
  ["retreat", "to withdraw from a position you were holding", 5],
  ["pursue", "to follow something in order to catch it", 4],
  ["release", "to let go of something you were holding", 3],
  ["carry", "to hold something and take it with you", 3],
  ["climb", "to go up something using effort", 3],
  ["swim", "to move through water under your own power", 1],
  ["dance", "to move your body in time with music", 1],
  ["sing", "to make music with your voice", 1],
  ["shout", "to say something at full volume", 1],
  ["whisper", "to speak so quietly only the nearest can hear", 2],
  ["laugh", "to make the sound of being amused", 1],
  ["stare", "to look at something fixedly and too long", 2],
  ["search", "to look carefully for something you cannot find", 5],
  ["discover", "to find something that was there all along", 2],
  ["invent", "to make something that never existed before", 1],
  ["memorize", "to commit something to memory deliberately", 4],
  ["forget", "to lose hold of something you knew", 5],
  ["remember", "to bring back to mind something from before", 4],
  ["realize", "to become aware of something that was already true", 5],
  ["betray", "to break faith with someone who trusted you", 2],
  ["confess", "to admit to something you would rather hide", 5],
  ["admit", "to concede that something is true", 5],
  ["deny", "to state that something is not so", 3],
  ["pretend", "to behave as though something were true when it is not", 5],
  ["perform", "to carry something out in front of an audience", 2],
  ["rest", "to stop working and let yourself recover", 2],
  ["breathe", "to draw air in and let it out", 1],
  ["arrive", "to reach the place you were going", 2],
  ["depart", "to leave a place, usually on a journey", 4],
  ["return", "to come back to where you started", 4],
  ["visit", "to go and spend time with someone or somewhere", 2],
  ["welcome", "to receive someone gladly", 4],
  ["travel", "to go from one place to a distant other", 1],
  ["explore", "to go through unfamiliar ground to see what is there", 3],
  ["navigate", "to work out and follow a route", 5],
  ["drift", "to be carried along without steering", 5],
  ["launch", "to send something off on its way", 1],
  ["aim", "to point at what you intend to hit", 4],
  ["persist", "to keep at it when it would be easier to stop", 5],
  ["finish", "to bring something to its end", 4],
  ["abandon", "to leave something for good, unfinished", 3],
  ["postpone", "to move something to a later time", 5],
  ["rush", "to do something faster than it should be done", 1],
  ["pause", "to stop briefly, meaning to carry on", 5],
  ["restart", "to begin again from the beginning", 4],
  ["simplify", "to strip something back to what matters", 5],
  ["clarify", "to make plain what was murky", 5],
  ["summarize", "to give the substance of something in short", 5],
  ["describe", "to put into words what something is like", 5],
  ["define", "to state exactly what something means", 5],
  ["compare", "to set two things side by side and note the difference", 5],
  ["count", "to work out how many there are", 4],
  ["estimate", "to judge a quantity roughly, without measuring", 5],
  ["predict", "to say what will happen before it does", 4],
  ["reflect", "to think something over carefully afterwards", 4],
  ["wish", "to want something you may not get", 4],
  ["crave", "to want something with an urgency close to need", 4],
  ["resist", "to push back against a force or a temptation", 4],
  ["tolerate", "to put up with something you do not like", 5],
  ["ignore", "to know something is there and give it nothing", 4],
  ["admire", "to regard someone with warm respect", 3],
  ["inspire", "to make someone want to act", 3],
  ["encourage", "to give someone the nerve to go on", 3],
  ["guide", "to show someone the way through", 4],
  ["obey", "to do what you have been told", 5],
  ["rebel", "to refuse the authority you are under", 3],
  ["vote", "to register your choice in a decision", 3],
  ["donate", "to give something away to a cause", 4],
  ["lend", "to let someone use what is yours for a while", 5],
  ["repay", "to give back what you owed", 5],
  ["save", "to keep something back rather than spend it", 3],
  ["spend", "to use up money or time", 4],
  ["earn", "to get something by working for it", 3],
  ["bargain", "to argue over a price until both sides accept", 1],
  ["settle", "to bring something unresolved to an end", 5],
  ["merge", "to join two things into one", 5],
  ["separate", "to move two things apart", 4],
  ["marry", "to commit to someone formally and publicly", 1],
  ["greet", "to acknowledge someone on meeting them", 4],
  ["introduce", "to make two people known to each other", 4],
  ["entertain", "to hold people's attention and give them pleasure", 2],
  ["tease", "to make fun of someone, usually kindly", 4],
  ["soothe", "to calm someone who is upset", 5],
  ["heal", "to make whole again what was damaged", 2],
  ["nourish", "to give what is needed to grow", 3],
  ["cook", "to prepare food with heat", 1],
  ["serve", "to do what is needed for someone else", 4],
  ["polish", "to rub something until it shines", 3],
  ["sculpt", "to shape a material into a form", 3],
  ["compose", "to put together a piece of music or writing", 5],
  ["edit", "to cut and reshape work until it is better", 5],
  ["publish", "to put work out where anyone can see it", 4],
  ["study", "to work at learning something", 3],
  ["graduate", "to complete a course of study and be recognised for it", 2],
  ["interview", "to question someone formally to find out about them", 2],
  ["resign", "to give up a post of your own accord", 5],
  ["retire", "to stop working for good", 4],
];

/** Adjectives. You have to find the thing before you can describe it. */
const QUALITY: Entry[] = [
  ["cultural", "relating to the customs and arts of a society", 4],
  ["fragile", "easily broken or damaged", 5],
  ["reckless", "acting without regard for the danger", 3],
  ["invisible", "unable to be seen", 5],
  ["temporary", "lasting only for a limited time", 5],
  ["loud", "producing a lot of noise", 2],
  ["expensive", "costing a great deal", 1],
  ["honest", "truthful and not deceiving", 4],
  ["awkward", "causing or feeling embarrassment or difficulty", 4],
  ["brave", "willing to face danger or pain", 3],
  ["cheap", "costing little, or of poor quality", 5],
  ["distant", "far away in space, time, or feeling", 5],
  ["empty", "containing nothing", 3],
  ["familiar", "well known to you from before", 5],
  ["generous", "giving more than is expected", 2],
  ["heavy", "weighing a lot, or hard to bear", 4],
  ["impossible", "not able to happen or be done", 5],
  ["lazy", "unwilling to work or use effort", 4],
  ["modern", "belonging to the present time", 3],
  ["nervous", "anxious about what is about to happen", 4],
  ["perfect", "having no flaw at all", 4],
  ["quiet", "making little or no noise", 4],
  ["rare", "not found or occurring often", 4],
  ["sharp", "having a fine edge, or quick to understand", 2],
  ["tired", "in need of rest or sleep", 4],
  ["warm", "moderately hot, or friendly in manner", 2],
  ["young", "having lived only a short time", 3],
  ["ancient", "belonging to the very distant past", 4],
  ["bitter", "sharp and unpleasant in taste, or resentful", 3],
  ["careless", "not giving enough attention to what you do", 5],
  ["dangerous", "likely to cause harm", 2],
  ["elegant", "graceful and pleasingly simple", 3],
  ["fake", "made to look real when it is not", 3],
  ["gentle", "mild and careful in manner", 3],
  ["hidden", "kept out of sight", 3],
  ["ideal", "as good as it could possibly be", 5],
  ["jealous", "resentful of a rival, or of what someone else has", 2],
  ["kind", "considerate and warm towards others", 3],
  ["lucky", "having good things happen by chance", 3],
  ["messy", "untidy and disordered", 2],
  ["natural", "existing in nature rather than made by people", 5],
  ["ordinary", "with nothing special about it", 5],
  ["polite", "showing good manners towards others", 5],
  ["reliable", "able to be depended on", 4],
  ["slow", "moving or happening at low speed", 4],
  ["true", "in accordance with fact", 3],
  ["urgent", "needing immediate attention", 3],
  ["vivid", "strikingly bright or clear in the mind", 4],
  ["wild", "living or growing without being controlled", 3],
  ["bright", "giving out much light, or quick-witted", 1],
  ["complicated", "made of many parts and hard to follow", 3],
  ["delicate", "finely made and easily harmed", 5],
  ["efficient", "getting the result with little waste", 5],
  ["free", "not under anyone's control, or costing nothing", 2],
  ["grateful", "feeling thankful for something received", 4],
  ["humble", "not thinking yourself better than others", 5],
  ["intense", "extreme in strength or feeling", 3],
  ["loyal", "faithful to a person or cause", 4],
  ["narrow", "small from side to side, or limited in outlook", 4],
  ["old", "having existed for a long time", 3],
  ["beautiful", "pleasing to look at to an unusual degree", 2],
  ["ugly", "unpleasant to look at", 2],
  ["clean", "free of dirt and marks", 3],
  ["dirty", "covered or marked with dirt", 1],
  ["noisy", "making more sound than is wanted", 1],
  ["calm", "untroubled and without agitation", 3],
  ["chaotic", "in complete disorder", 4],
  ["simple", "easily understood, with nothing extra", 5],
  ["subtle", "so slight that it is easily missed", 5],
  ["bold", "willing to take a risk in the open", 3],
  ["timid", "lacking the nerve to step forward", 4],
  ["confident", "sure of yourself and showing it", 2],
  ["stubborn", "refusing to change your mind or your course", 5],
  ["flexible", "able to bend or adjust without breaking", 3],
  ["rigid", "unable to bend, and unwilling to", 2],
  ["strict", "insisting the rules be kept exactly", 4],
  ["fair", "treating everyone by the same measure", 4],
  ["sincere", "meaning what you say", 5],
  ["sarcastic", "saying the opposite of what you mean, to sting", 4],
  ["funny", "causing laughter", 1],
  ["serious", "not joking, and not to be taken lightly", 5],
  ["playful", "light-hearted and up for a game", 1],
  ["cheerful", "noticeably in good spirits", 2],
  ["gloomy", "dark, or low in mood", 4],
  ["hopeful", "expecting that things may still turn out well", 3],
  ["anxious", "uneasy about what might happen", 3],
  ["relaxed", "free of tension", 3],
  ["tense", "stretched tight, in body or in mood", 2],
  ["comfortable", "at ease, with nothing pressing on you", 3],
  ["secure", "safe, and feeling it", 3],
  ["exposed", "open to being seen or harmed", 3],
  ["private", "kept away from other people", 5],
  ["public", "open to everyone", 5],
  ["hollow", "having an empty space inside", 4],
  ["solid", "firm all the way through", 3],
  ["soft", "yielding to the touch", 2],
  ["rough", "uneven to the touch, or lacking gentleness", 1],
  ["smooth", "even to the touch, with no catch", 3],
  ["slippery", "hard to keep hold of, or to stand on", 2],
  ["dry", "with no moisture in it", 4],
  ["wet", "soaked or covered with liquid", 1],
  ["freezing", "cold enough to turn water to ice", 1],
  ["dark", "with little or no light", 3],
  ["pale", "light in colour, or drained of it", 3],
  ["dull", "not bright, or not interesting", 4],
  ["shiny", "reflecting light from its surface", 3],
  ["faded", "having lost its colour or force over time", 3],
  ["worn", "showing the wear of long use", 2],
  ["broken", "no longer whole, no longer working", 1],
  ["cracked", "split but not yet in pieces", 2],
  ["sturdy", "strongly built and not easily upset", 4],
  ["flimsy", "too weak or thin to be relied on", 4],
  ["enormous", "very much larger than usual", 3],
  ["tall", "of greater height than most", 3],
  ["deep", "extending far down from the surface", 4],
  ["shallow", "not extending far down, in water or in thought", 3],
  ["thick", "of great width between its two surfaces", 3],
  ["crowded", "holding more people than it comfortably fits", 3],
  ["busy", "with a great deal to do", 5],
  ["idle", "not being used, not doing anything", 5],
  ["sudden", "happening without warning", 4],
  ["gradual", "happening slowly, by degrees", 5],
  ["constant", "going on without a break", 5],
  ["permanent", "lasting indefinitely", 5],
  ["endless", "seeming to have no end", 5],
  ["brief", "lasting only a short time", 5],
  ["early", "before the expected time", 4],
  ["late", "after the time it should have been", 2],
  ["absent", "not there when you should be", 5],
  ["missing", "not where it should be, and not found", 4],
  ["lost", "unable to be found, or unable to find your way", 2],
  ["forgotten", "no longer remembered by anyone", 5],
  ["memorable", "of the kind that stays with people", 4],
  ["famous", "known to a great many people", 5],
  ["unknown", "not recognised by anyone", 5],
  ["popular", "liked by most people", 5],
  ["rich", "having a great deal of money", 1],
  ["poor", "having very little money", 3],
  ["valuable", "worth a great deal", 4],
  ["worthless", "of no value at all", 3],
  ["useful", "able to be put to good use", 4],
  ["useless", "serving no purpose", 4],
  ["necessary", "required, with no way around it", 5],
  ["common", "found or happening often", 5],
  ["unique", "the only one of its kind", 4],
  ["strange", "unfamiliar in a way that unsettles", 5],
  ["normal", "as things usually are", 5],
  ["selfish", "putting yourself first at others' cost", 4],
  ["cruel", "willing to cause pain", 3],
  ["harsh", "severe, with no softness in it", 3],
  ["tender", "gentle in a way that shows care", 4],
  ["tough", "hard to break, or hard to get through", 5],
  ["weak", "lacking strength", 2],
  ["powerful", "able to make things happen", 3],
  ["helpless", "unable to do anything about it", 3],
  ["clumsy", "awkward in movement, prone to knocking things over", 4],
  ["graceful", "moving with ease and beauty", 4],
  ["skilled", "practised enough to do it well", 3],
  ["experienced", "having done it many times before", 5],
  ["naive", "lacking the experience to see what is coming", 5],
  ["foolish", "showing poor judgement", 4],
  ["clever", "quick to understand and work things out", 3],
  ["thoughtful", "given to thinking, or considerate of others", 4],
  ["cautious", "careful to avoid risk", 5],
  ["spontaneous", "done on impulse, without planning", 3],
  ["predictable", "easy to see coming", 5],
  ["surprising", "not at all what was expected", 3],
  ["boring", "failing to hold any interest", 4],
  ["fascinating", "holding your interest completely", 3],
  ["inspiring", "making people want to act", 5],
  ["mediocre", "neither good nor bad, and forgettable for it", 5],
  ["stale", "no longer fresh, whether bread or an idea", 3],
];

export type WordCard = {
  word: string;
  category: WordCategory;
  definition: string;
  /** 1 is easiest to speak on, 5 is hardest. See TIER_LABEL. */
  tier: number;
};

export const TIER_LABEL: Record<number, string> = {
  1: "warm-up",
  2: "everyday",
  3: "mixed",
  4: "abstract",
  5: "cold open",
};

const POOL: WordCard[] = [
  ...CONCRETE.map(([word, definition, tier]) => ({ word, definition, tier, category: "concrete" as const })),
  ...ABSTRACT.map(([word, definition, tier]) => ({ word, definition, tier, category: "abstract" as const })),
  ...ACTION.map(([word, definition, tier]) => ({ word, definition, tier, category: "action" as const })),
  ...QUALITY.map(([word, definition, tier]) => ({ word, definition, tier, category: "quality" as const })),
];

export function poolByTier() {
  const counts: Record<number, number> = {};
  for (const entry of POOL) counts[entry.tier] = (counts[entry.tier] ?? 0) + 1;
  return counts;
}

export const WORD_POOL_SIZE = POOL.length;

/**
 * Pick a word at the speaker's level.
 *
 * Most draws come from the level's own tier, but one in five reaches a tier
 * higher and one in ten drops a tier lower — a fixed difficulty gets stale, and
 * an occasional word you are not ready for is the point of the drill.
 *
 * `recent` is excluded so a session never repeats itself.
 */
export function randomWord({
  level = 1,
  recent = [],
}: { level?: number; recent?: string[] } = {}): WordCard {
  const clamped = Math.max(1, Math.min(5, Math.round(level)));
  const roll = Math.random();
  const target =
    roll < 0.2 ? Math.min(5, clamped + 1) : roll < 0.3 ? Math.max(1, clamped - 1) : clamped;

  const avoid = new Set(recent);
  const inTier = POOL.filter((entry) => entry.tier === target && !avoid.has(entry.word));
  const anyTier = POOL.filter((entry) => entry.tier === target);
  const fresh = POOL.filter((entry) => !avoid.has(entry.word));

  const source =
    inTier.length > 0 ? inTier : anyTier.length > 0 ? anyTier : fresh.length > 0 ? fresh : POOL;
  return source[Math.floor(Math.random() * source.length)];
}
